[tool.poetry]
name = "beancount-importer"
version = "0.1.0"
description = "Various beancount importers"
readme = "README.rst"

repository = "https://github.com/TheKevJames/beancount-importer"
authors = ["Kevin James <beancount-importer@thekev.in>"]
license = "MIT"

packages = [
    { include = "beancount_importer" },
]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
beancount = "2.3.5"
openpyxl = "3.1.2"
py-pdf-parser = "0.10.2"
python-dateutil = "2.8.2"
titlecase = "2.4"

[[tool.mypy.overrides]]
module = [
    'beancount.core.*',
    'beancount.ingest.*',
    'py_pdf_parser.*',
    'titlecase.*',
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
